### ISSUE TITLE
Selective test runs

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak-gh-actionbot#3]
### Description

We're constantly facing issues with GHA test runs due to limited resources and as a result the required time it takes to finish all test runs. The bot could be leveraged to solved this. The default test matrices would be limited to selected basic tests (e.g. only base testsuite). Other tests would be ran by the bot when explicitly asked for it by a reviewer.

**Comment by stianst** [comment]
We'd want to discuss this before going down this path. I believe this is a fairly complex thing to implement, and also not ideal as it requires human intervention. I can easily see something like this actually resulting in it taking longer from a PR is submitted until it is sufficiently tested. Say a high proportion of PRs need additional testing then you end up with "wait for base tests + wait for human to decide what additional testing + wait for additional testing".

I think there are other and better strategies we can apply to improve on the current situation.

**Comment by ahus1** [comment]
Closing this upon @stianst comment.
